server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location ~ ^/(process|preview|thumbnail) {
    proxy_pass ${BACKEND_URL};
    client_max_body_size 50m;
  }
}
